[workspace]

members = [
    "g_token",
    "g_token/meta",
   
    "liquid-staking",
    "liquid-staking/meta",
   
    "akf-mock",
    "akf-mock/meta",
   
    "delegation-proxy-mock",
    "delegation-proxy-mock/meta",

    "fuzz"
]