// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback:                       1
// Total number of exported functions:  13

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    g_token
    (
        init => init
        registerGToken => register_g_token
        mint => mint
        burn => burn
        pair_add_initial_liquidity => pair_add_initial_liquidity
        getPairGRatio => pair_g_ratio
        getGPairInfo => pair_info
        getGPairs => pair_map
        getGTokenID => g_token
        router_create_pair => router_create_pair
        router_issue_lp => router_issue_lp
        router_set_lp_local_roles => router_set_lp_local_roles
    )
}

multiversx_sc_wasm_adapter::async_callback! { g_token }
