// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           14
// Async Callback:                       1
// Total number of exported functions:  16

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        addLiquidity => add_liquidity
        claim_reward => claim_reward
        remove_liquidity => remove_liquidity
        delegate => delegate
        try_claim_from_delegation_proxy => try_claim_from_delegation_proxy
        is_enough_to_delegate => is_enough_to_delegate
        totalClaimable => total_claimable
        lastClaim => last_claim
        getDSCAddress => get_dsc_address
        register_ls_token => register_ls_token
        getLsTokenId => ls_token
        topUpRewards => top_up_rewards
        getLsSupply => ls_token_supply
        getRewardPerShare => reward_per_share
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
