// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback:                       1
// Total number of exported functions:   9

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        init => init
        addLiquidity => add_liquidity
        delegate => delegate
        getDSCAddress => get_dsc_address
        register_ls_token => register_ls_token
        getLsTokenId => ls_token
        getLsSupply => ls_token_supply
        getRewardPerShare => reward_per_share
    )
}

multiversx_sc_wasm_adapter::async_callback! { liquid_staking }
