[package]
name = "liquid-staking-meta"
version = "0.0.0"
edition = "2021"
publish = false
[dependencies.liquid-staking]
path = ".."

[dependencies.multiversx-sc-meta]
git = "https://github.com/newtmex/mx-sdk-rs.git"
branch = "hackathon-feat"
